"""
Fixed configuration: AWS stack, frameworks, label colours, and methodology.
These are the same for every project generated by this tool.
"""

from dataclasses import dataclass, field
from typing import List


# ─── Tech stack (always the same) ────────────────────────────────────────────

TECH_STACK = {
    "frontend": "Angular 17+",
    "backend_api": "NestJS (Node.js)",
    "ai_service": "FastAPI (Python)",
    "database": "PostgreSQL",
    "cache": "Redis",
    "infra": "AWS",
}

AWS_SERVICES = {
    "frontend_hosting": "S3 + CloudFront",
    "backend_runtime": "ECS Fargate",
    "ai_runtime": "ECS Fargate (servicio separado)",
    "database": "RDS Aurora PostgreSQL Serverless v2",
    "cache": "ElastiCache Redis",
    "email_inbound": "SES + S3 + Lambda + SQS",
    "storage": "S3 (docs, fotos, contratos, facturas)",
    "ocr": "AWS Textract",
    "container_registry": "ECR",
    "load_balancer": "ALB (Application Load Balancer)",
    "cdn": "CloudFront + Route 53",
    "secrets": "AWS Secrets Manager",
    "monitoring": "CloudWatch + X-Ray",
    "ci_cd": "GitHub Actions → ECR → ECS rolling deploy",
    "network": "VPC privada + subnets privadas + NAT Gateway",
    "waf": "AWS WAF",
    "ssl": "ACM (certificados gratis)",
}

AWS_COST_ESTIMATE = """
| Servicio | Coste estimado/mes |
|---------|-------------------|
| ECS Fargate (NestJS + FastAPI) | ~90 – 150 € |
| RDS Aurora Serverless v2 | ~60 – 120 € |
| ElastiCache Redis | ~25 – 40 € |
| CloudFront + S3 | ~10 – 20 € |
| ALB | ~20 € |
| SES + Lambda + SQS | ~5 – 15 € |
| Secrets Manager + otros | ~10 € |
| **TOTAL** | **~220 – 375 €/mes** |
"""


# ─── GitHub label definitions ─────────────────────────────────────────────────

# Module colours cycling order
MODULE_COLORS = ["BLUE", "GREEN", "RED", "ORANGE", "PURPLE", "YELLOW"]

# Hex colours for GitHub labels
MODULE_HEX = {
    "BLUE":   "1D76DB",
    "GREEN":  "0E8A16",
    "RED":    "E11D48",
    "ORANGE": "F97316",
    "PURPLE": "5319E7",
    "YELLOW": "E4E669",
}

# Project-level single-select field option colours (GitHub Projects v2)
MODULE_PROJECT_COLORS = {
    "BLUE":   "BLUE",
    "GREEN":  "GREEN",
    "RED":    "RED",
    "ORANGE": "ORANGE",
    "PURPLE": "PURPLE",
    "YELLOW": "YELLOW",
}

BASE_LABELS = [
    {"name": "bloqueante",      "color": "B60205", "description": "Tarea bloqueante — requiere respuesta del cliente"},
    {"name": "cliente",         "color": "F97316", "description": "Acción requerida del cliente"},
    {"name": "prioridad-1",     "color": "D93F0B", "description": "Prioridad máxima"},
    {"name": "infraestructura", "color": "5319E7", "description": "Infraestructura y setup"},
    {"name": "backend",         "color": "0075CA", "description": "Backend development"},
    {"name": "frontend",        "color": "008672", "description": "Frontend development"},
    {"name": "ia-ml",           "color": "E4E669", "description": "IA / Machine Learning"},
    {"name": "integracion",     "color": "F9D0C4", "description": "Integración con sistemas externos"},
]


# ─── Project board configuration ─────────────────────────────────────────────

# Status column options
STATUS = {
    "backlog":     "Backlog",
    "ready":       "Ready",
    "in_progress": "In progress",
    "in_review":   "In review",
    "done":        "Done",
}

# Priority field options
PRIORITY = {
    "P0": "P0",  # client blockers
    "P1": "P1",  # foundational dev tasks
    "P2": "P2",  # secondary dev tasks
}


# ─── Methodology constants ────────────────────────────────────────────────────

# Days from today for client blocker deadlines
BLOCKER_DEADLINE_DAYS = {
    "critical": 4,   # API access, accounts — blocking everything
    "high":     7,   # Data, credentials — blocking module start
    "medium":  10,   # Rules, workflows — blocking detailed design
}

# Weeks from today for dev task deadlines
DEV_DEADLINE_WEEKS = {
    1: 2,   # Sprint 1 → 2 weeks
    2: 4,   # Sprint 2 → 4 weeks
    3: 6,   # Sprint 3 → 6 weeks
    4: 8,   # Sprint 4 → 8 weeks (final)
}

# Size → GitHub project Size field
SIZE_MAP = {
    "XS": "XS",
    "S":  "S",
    "M":  "M",
    "L":  "L",
    "XL": "XL",
}
